twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        form_service : '@App\Service\FormService'
        
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
